version: '3.8'

services:
  app:
    build:
      context: ./backend
    container_name: laravel_app
    command: bash -c "php artisan migrate && apache2-foreground"
    ports:
      - "8080:80"
    volumes:
      - ./backend/src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  dbdata:
