version: '3.8'

services:
  # PHP-FPM (Laravel) サービス
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./laravel-app:/var/www
    networks:
      - laravel
    depends_on:
      - db
    command: sh -c "php artisan migrate --force && php-fpm"

  # Nginx サービス
  nginx:
    image: nginx:latest
    container_name: nginx_server
    volumes:
      - ./laravel-app:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - laravel

  # MySQL (オプション)
  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    volumes:
      - dbdata:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - laravel
    ports:
      - "3306:3306"

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
    driver: local
